  // Get Data Action //
export const PRODUCT_DATA_PROGRESS ="PRODUCT_DATA_PROGRESS";
export const PRODUCT_DATA_SUCCESS ="PRODUCT_DATA_SUCCESS";
export const PRODUCT_DATA_ERROR ="PRODUCT_DATA_ERROR";

// Delete Data Action //

export const DELETE_DATA_PROGRESS ="DELETE_DATA_PROGRESS";
export const DELETE_DATA_SUCCESS ="DELETE_DATA_SUCCESS";
export const DELETE_DATA_ERROR ="DELETE_DATA_ERROR";