 // Get Data Action //
export const PRODUCT_DATA_PROGRESS ="PRODUCT_DATA_PROGRESS";
export const PRODUCT_DATA_SUCCESS ="PRODUCT_DATA_SUCCESS";
export const PRODUCT_DATA_ERROR ="PRODUCT_DATA_ERROR";

// Delete Data Action //

export const DELETE_DATA_PROGRESS ="DELETE_DATA_PROGRESS";
export const DELETE_DATA_SUCCESS ="DELETE_DATA_SUCCESS";
export const DELETE_DATA_ERROR ="DELETE_DATA_ERROR";

  // Get Data Action //
  export const ADD_TO_CART_PROGRESS ="ADD_TO_CART_PROGRESS";
  export const ADD_TO_CART_SUCCESS ="ADD_TO_CART_SUCCESS";
  export const ADD_TO_CART_ERROR ="ADD_TO_CART_ERROR";

    // Update Data Action //
    export const UPADTE_DATA_PROGRESS ="UPADTE_DATA_PROGRESS";
    export const UPADTE_DATA_SUCCESS ="UPADTE_DATA_SUCCESS";
    export const UPADTE_DATA_ERROR ="UPADTE_DATA_ERROR";