// Get User Data Action //

export const GET_USER_PROGRESS = "GET_USER_PROGRESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

// Delete User  Action //

export const DELETE_USER_PROGRESS = "DELETE_USER_PROGRESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";

// Update User  Action //

export const UPDATE_USER_PROGRESS = "UPDATE_USER_PROGRESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

// Add User  Action //

export const ADD_USER_PROGRESS = "ADD_USER_PROGRESS";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_ERROR = "ADD_USER_ERROR";

// Add PARTY  Action //

export const ADD_PARTY_PROGRESS = "ADD_PARTY_PROGRESS";
export const ADD_PARTY_SUCCESS = "ADD_PARTY_SUCCESS";
export const ADD_PARTY_ERROR = "ADD_PARTY_ERROR";

// GEt PARTY  Action //

export const GET_PARTY_PROGRESS = "GET_PARTY_PROGRESS";
export const GET_PARTY_SUCCESS = "GET_PARTY_SUCCESS";
export const GET_PARTY_ERROR = "GET_PARTY_ERROR";
